# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-14 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_foodtypes_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('userPassword', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('userPhonenumber', models.CharField(max_length=20)),
                ('userAddress', models.CharField(max_length=100)),
                ('userImg', models.CharField(max_length=150)),
                ('userRank', models.IntegerField()),
                ('userToken', models.CharField(max_length=50)),
            ],
        ),
    ]
