# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-15 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='userAccount',
            field=models.CharField(max_length=20),
        ),
    ]
