# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-25 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='phonenum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='receiveaddress',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.CharField(default='', max_length=20),
        ),
    ]
