# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-25 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20181225_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phonenum',
            field=models.CharField(max_length=20),
        ),
    ]
