# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-02-03 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_orderproducts_userticketmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTicketModel',
            new_name='UserTicket',
        ),
    ]
