# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-02-03 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_auto_20200203_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Cart'),
        ),
    ]
